# version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://fuel_user:fuel_pass@db:5432/fuel_efficiency_db
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - model_data:/app/ml_models
    networks:
      - fuel-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
    networks:
      - fuel-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=fuel_efficiency_db
      - POSTGRES_USER=fuel_user
      - POSTGRES_PASSWORD=fuel_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fuel-network

volumes:
  postgres_data:
  model_data:

networks:
  fuel-network:
    driver: bridge